/* Generated by the Systemtap dtrace wrapper */

#define _SDT_HAS_SEMAPHORES 1


#define STAP_HAS_SEMAPHORES 1 /* deprecated */


#include <sys/sdt.h>

/* BACKEND_SGX_ECALL_START ( int) */
#if defined STAP_SDT_V1
#define BACKEND_SGX_ECALL_START_ENABLED() __builtin_expect (ecall_start_semaphore, 0)
#define backend_sgx_ecall_start_semaphore ecall_start_semaphore
#else
#define BACKEND_SGX_ECALL_START_ENABLED() __builtin_expect (backend_sgx_ecall_start_semaphore, 0)
#endif
__extension__ extern unsigned short backend_sgx_ecall_start_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define BACKEND_SGX_ECALL_START(arg1) \
DTRACE_PROBE1(backend_sgx,ecall_start,arg1)

/* BACKEND_SGX_ECALL_FINISH ( int) */
#if defined STAP_SDT_V1
#define BACKEND_SGX_ECALL_FINISH_ENABLED() __builtin_expect (ecall_finish_semaphore, 0)
#define backend_sgx_ecall_finish_semaphore ecall_finish_semaphore
#else
#define BACKEND_SGX_ECALL_FINISH_ENABLED() __builtin_expect (backend_sgx_ecall_finish_semaphore, 0)
#endif
__extension__ extern unsigned short backend_sgx_ecall_finish_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define BACKEND_SGX_ECALL_FINISH(arg1) \
DTRACE_PROBE1(backend_sgx,ecall_finish,arg1)

/* BACKEND_SGX_IOBUF_START ( int) */
#if defined STAP_SDT_V1
#define BACKEND_SGX_IOBUF_START_ENABLED() __builtin_expect (iobuf_start_semaphore, 0)
#define backend_sgx_iobuf_start_semaphore iobuf_start_semaphore
#else
#define BACKEND_SGX_IOBUF_START_ENABLED() __builtin_expect (backend_sgx_iobuf_start_semaphore, 0)
#endif
__extension__ extern unsigned short backend_sgx_iobuf_start_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define BACKEND_SGX_IOBUF_START(arg1) \
DTRACE_PROBE1(backend_sgx,iobuf_start,arg1)

/* BACKEND_SGX_IOBUF_FINISH ( int) */
#if defined STAP_SDT_V1
#define BACKEND_SGX_IOBUF_FINISH_ENABLED() __builtin_expect (iobuf_finish_semaphore, 0)
#define backend_sgx_iobuf_finish_semaphore iobuf_finish_semaphore
#else
#define BACKEND_SGX_IOBUF_FINISH_ENABLED() __builtin_expect (backend_sgx_iobuf_finish_semaphore, 0)
#endif
__extension__ extern unsigned short backend_sgx_iobuf_finish_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define BACKEND_SGX_IOBUF_FINISH(arg1) \
DTRACE_PROBE1(backend_sgx,iobuf_finish,arg1)

