/* Generated by the Systemtap dtrace wrapper */

#define _SDT_HAS_SEMAPHORES 1


#define STAP_HAS_SEMAPHORES 1 /* deprecated */


#include <sys/sdt.h>

/* BACKEND_SGX_ECALL_START ( char * op) */
#if defined STAP_SDT_V1
#define BACKEND_SGX_ECALL_START_ENABLED() __builtin_expect (ecall__start_semaphore, 0)
#define backend_sgx_ecall__start_semaphore ecall__start_semaphore
#else
#define BACKEND_SGX_ECALL_START_ENABLED() __builtin_expect (backend_sgx_ecall__start_semaphore, 0)
#endif
__extension__ extern unsigned short backend_sgx_ecall__start_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define BACKEND_SGX_ECALL_START(arg1) \
DTRACE_PROBE1(backend_sgx,ecall__start,arg1)

/* BACKEND_SGX_ECALL_FINISH () */
#if defined STAP_SDT_V1
#define BACKEND_SGX_ECALL_FINISH_ENABLED() __builtin_expect (ecall__finish_semaphore, 0)
#define backend_sgx_ecall__finish_semaphore ecall__finish_semaphore
#else
#define BACKEND_SGX_ECALL_FINISH_ENABLED() __builtin_expect (backend_sgx_ecall__finish_semaphore, 0)
#endif
__extension__ extern unsigned short backend_sgx_ecall__finish_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define BACKEND_SGX_ECALL_FINISH() \
DTRACE_PROBE(backend_sgx,ecall__finish)

